--system/root

--create tablespace
CREATE TABLESPACE mydata
	DATAFILE 'C:\ORACLEXE\APP\ORACLE\ORADATA\XE\mydata.DBF'
	SIZE 123M
    AUTOEXTEND ON NEXT 500K MAXSIZE 1024M;

--create db user
CREATE USER whisper
IDENTIFIED BY "whisper"
DEFAULT TABLESPACE mydata
TEMPORARY TABLESPACE temp

GRANT DBA TO whisper ;
GRANT UNLIMITED TABLESPACE TO whisper ;
